### PR TITLE
Bug & Error Fixes

### PR DESCRIPTION
**Pull request by pbnj**
- Added `package.json` to fix issues #24 & #30 (lock in latest LTS version of node.js & install missing `websocket` dependency).
  - If you feel that these issues are better served if the [Arrow Functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) are replaced by the traditional function syntax, I can go through the code and make the necessary changes.
  - Otherwise, the installation instructions might need to be updated to walk users through installing more recent version of NodeJS.
- Installed linter & fixed styling inconsistencies which can lead to hard-to-detect bugs (to run linter: `npm run lint` within the project)
- Miscellaneous bug & error fixing in code (e.g. `for-in` loops, missing semi-colons)

### CODE REVIEW

**Comment by samyk** [comment]
Awesome updates, thank you! Couple things:

- target_backdoor.js is sent to the target browser so it may not support ES6 (backticks)
- I haven't decided on a license yet so happy to accept but without a license defined (I could accept the pull and then change the license, but that seems uncivil)

**Comment by pbnj** [comment]
@samyk Thank you for the feedback.
- Replaced template strings (backticks) with single quotes in `target_backdoor.js`
- Replaced the default `ISC` license in package.json to `UNLICENSED`

**Comment by samyk** [comment]
Great -- I'd like to merge this but haven't had a chance to test it. Have you performed any testing on this?

**Comment by pbnj** [comment]
I haven't had a chance to test it, but it looks like there are some merge conflicts now. I'll have to go through and resolve these conflicts first.

**Comment by pbnj** [comment]
Merge conflicts resolved. I apologize, though, I haven't had a chance to test the changes.

**Comment by samyk** [comment]
Thanks -- I'll try to test this weekend

**Pull request closed without merging**
