### PR TITLE
Actually poison the user's cache of common JS files from CDNs

### PR DESCRIPTION
**Pull request by HxxxxxS**
From target_injected_xhtmljs.html:
`/* First poison the user's cache of common JS files from CDNs */`,
however, this is not done unless the JS is requested elsewhere. Added a function to request all the JS files in js/ before backdooring routers and siphoning cookies.

### CODE REVIEW

**Comment by samyk** [comment]
Awesome, thanks! You're right, previously only replaced the JS if it's requested during PoisonTap usage - useful update

**Comment by Montana420** [comment]
Hi i'm receiving the following. Could it be in relation to this?
Screen Shot 2019-06-01 at 7 37 38 pm

**Comment by itsecstudy** [comment]
@Montana552 did you ever manage to solve this? I am getting the same and not siphoning cookies, trying to get this working now. Thanks

**Comment by Montana420** [comment]
Unfortunately not, have no idea where the SD is containing this. I'll have to start fresh and again when i have some time. Maybe patched?

**Pull request merged**
